# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# https://hub.docker.com/r/gettyimages/spark/tags
Master:
  Name: master
  Image: "gettyimages/spark"
  ImageTag: "2.3.1-hadoop-3.0"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePortName: service
  ServicePort: 7077
  ServiceContainerPort: 7077
  RestPortName: rest
  RestPort: 6066
  RestContainerPort: 6066
  # Set Master JVM memory. Default 1g
  #DaemonMemory: 1g

WebUi:
  Name: webui
  ServicePort: 8080
  ContainerPort: 8080
  IngressClass: tectonic
  Domain: k8s.test

Worker:
  Name: worker
  Image: "gettyimages/spark"
  ImageTag: "2.3.1-hadoop-3.0"
  Replicas: 3
  Component: "spark-worker"
  Cpu: "100m"
  Memory: "512Mi"
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  #DaemonMemory: 1g
  # Set how much total memory workers have to give executors
  #ExecutorMemory: 1g

